format = """
[](#CAAE48)\
[ğ–—ğ–†ğ–“ğ–Œğ–Šğ–—](#CAAE48)\
[ ](fg:#CAAE48)\
[on](fg:#CAAE48)\
$directory\
[](fg:#CAAE48)\
$git_branch\
$git_status\
[](fg:#CAAE48)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736)\ 
[](fg:#1d2230)\ 
[ $fill](fg:#a0a9cb)[](#a3aed2)$time\
[](#1d2230)\ 
\n$character"""


[directory]
style = "fg:#CAAE48"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = ""

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"Home" = "ï€•"
"~" = "î»º "

[git_branch]
symbol = "ï˜"
style = "fg:#CAAE48"
format = '[[ $symbol $branch ](fg:#769ff0)]($style)'

[git_status]
style = "fg:#CAAE48"
format = '[[($all_status$ahead_behind)](fg:#769ff0)]($style)'



[nodejs]
symbol = "îœ˜"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = "î¨"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[fill]
symbol = " "
style = "fg:#ffffff" 



[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time](fg:#CAAE48)]($style)'




[character]
format = ''
